// Asset Inventory — session-based physical counting/verification, the admin
// screen for the Assets Management module (FourthUpdate.md).
// Route: admin/asset-inventory · permission: Assets.Inventory · rank 3.
//
// Flow: list sessions -> create a Draft session (bilingual name, date range,
// custody units in scope, member users) -> start it -> scan assets one at a
// time against their expected custody unit/custodian/last transaction
// (result: Found/Damaged/WrongLocation/WrongCustodian/NeedsMaintenance/
// Disposed/UnexpectedAsset/BarcodeMissing — never Missing, that is
// system-generated only) -> complete the session, which shows a summary of
// counts by result_status including how many rows were auto-generated as
// Missing by asset_inventory_session_complete().
//
// Data access only through src/data/assetsService.js, plus loadRecipients()
// from approvalService.js for the employee directory — the exact same reuse
// every other admin screen already makes for that list (ApprovalAdmin.jsx,
// ApprovalChain.jsx).

import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import {
  AlertTriangle, ArrowLeft, Barcode, Boxes, Calendar, Check, ClipboardCheck, ClipboardList,
  Eye, ListChecks, Package, PackageSearch, Play, Plus, RefreshCcw, Search, Users, X,
} from 'lucide-react';
import { useLanguage } from '../../context/LanguageContext';
import { useTenant } from '../../context/TenantContext';
import { useDialogA11y } from '../../utils/useDialogA11y';
import { formatDate, formatDateTime, pickLocalized } from '../../utils/localize';
import { loadRecipients } from '../../data/approvalService';
import AttachmentsPanel from '../platform/AttachmentsPanel';
import { SESSION_STATUS_KEYS } from './assetsVocabulary';
import {
  INVENTORY_SCAN_RESULTS,
  INVENTORY_SESSION_STATUSES,
  assetsErrorMessage,
  completeInventorySession,
  createInventorySession,
  listAssetAttachments,
  loadAssets,
  loadCustodyUnits,
  loadInventorySessionDetail,
  loadInventorySessions,
  loadLastMovementForAssets,
  recordInventoryScan,
  startInventorySession,
} from '../../data/assetsService';
import './assets.css';

// ---------------------------------------------------------------------------
// Local vocabulary maps — same pattern as ApprovalAdmin.jsx's STATUS_KEYS:
// codes are stored/compared as-is, only the label shown to a person is
// translated. Draft/InProgress/Cancelled reuse the platform-wide status_*
// vocabulary exactly (that is what they mean); 'Completed' has no existing
// generic equivalent (status_closed means something else) so it is the one
// module-owned addition.
// ---------------------------------------------------------------------------
const SESSION_STATUS_FILTERS = ['All', ...INVENTORY_SESSION_STATUSES];

// Every code asset_inventory_scan() accepts as a manual result. 'Missing' is
// deliberately excluded from the selectable set — the RPC itself rejects a
// manual 'Missing' scan (MISSING_IS_SYSTEM_GENERATED); it only ever appears
// already-recorded, generated by asset_inventory_session_complete().
const SELECTABLE_SCAN_RESULTS = INVENTORY_SCAN_RESULTS.filter((code) => code !== 'Missing');

const SCAN_RESULT_KEYS = {
  Found: 'assets_scan_found',
  Missing: 'assets_scan_missing',
  Damaged: 'assets_scan_damaged',
  WrongLocation: 'assets_scan_wronglocation',
  WrongCustodian: 'assets_scan_wrongcustodian',
  NeedsMaintenance: 'assets_scan_needsmaintenance',
  Disposed: 'assets_scan_disposed',
  UnexpectedAsset: 'assets_scan_unexpectedasset',
  BarcodeMissing: 'assets_scan_barcodemissing',
};

// asset_transactions can carry a few types createAssetTransaction() itself
// never writes (Dispose/MaintenanceOut/MaintenanceReturn come from the
// disposal and maintenance RPCs/triggers instead) — "last transaction" may
// legitimately show any of them.
const TRANSACTION_TYPE_KEYS = {
  Receive: 'assets_txn_receive', Issue: 'assets_txn_issue', Transfer: 'assets_txn_transfer',
  Return: 'assets_txn_return', Lost: 'assets_txn_lost', Found: 'assets_txn_found',
  Reserve: 'assets_txn_reserve', Release: 'assets_txn_release', Dispose: 'assets_txn_dispose',
  MaintenanceOut: 'assets_txn_maintenanceout', MaintenanceReturn: 'assets_txn_maintenancereturn',
};

const personName = (person, lang) => pickLocalized(person, 'name', lang) || person?.full_name || '';

const StatusBadge = ({ status }) => {
  const { t } = useLanguage();
  const key = SESSION_STATUS_KEYS[status];
  return <span className={`status-badge status-${String(status || '').toLowerCase()}`}>{key ? t(key) : status}</span>;
};

const ScanResultBadge = ({ result }) => {
  const { t } = useLanguage();
  const key = SCAN_RESULT_KEYS[result];
  return <span className={`scan-badge scan-${String(result || '').toLowerCase()}`}>{key ? t(key) : result}</span>;
};

const Notice = ({ notice, onDismiss }) => {
  const { t } = useLanguage();
  if (!notice) return null;
  return (
    <div className={`inline-message ${notice.tone === 'error' ? 'error' : ''}`} role="status" aria-live="polite">
      {notice.tone === 'error' ? <X aria-hidden="true" /> : <Check aria-hidden="true" />}
      {notice.text}
      <button type="button" onClick={onDismiss} aria-label={t('action_close')}><X aria-hidden="true" /></button>
    </div>
  );
};

// ---------------------------------------------------------------------------
// Create session modal — bilingual name, date range, custody-unit scope and
// member scope (each its own filterable checklist; a company may have far
// more custody units/employees than fit on screen at once).
// ---------------------------------------------------------------------------
const emptySessionDraft = () => ({
  name_ar: '', name_en: '', start_date: '', end_date: '', notes: '',
  custody_unit_ids: [], member_user_ids: [],
});

const CreateSessionModal = ({ custodyUnits, employees, lang, onClose, onCreated }) => {
  const { t } = useLanguage();
  const closeRef = useDialogA11y(onClose);
  const [draft, setDraft] = useState(emptySessionDraft);
  const [unitQuery, setUnitQuery] = useState('');
  const [memberQuery, setMemberQuery] = useState('');
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState('');

  const field = (key) => (event) => setDraft((current) => ({ ...current, [key]: event.target.value }));

  const toggleUnit = (id) => setDraft((current) => ({
    ...current,
    custody_unit_ids: current.custody_unit_ids.includes(id)
      ? current.custody_unit_ids.filter((item) => item !== id)
      : [...current.custody_unit_ids, id],
  }));
  const toggleMember = (id) => setDraft((current) => ({
    ...current,
    member_user_ids: current.member_user_ids.includes(id)
      ? current.member_user_ids.filter((item) => item !== id)
      : [...current.member_user_ids, id],
  }));

  const visibleUnits = useMemo(() => {
    const needle = unitQuery.trim().toLocaleLowerCase();
    if (!needle) return custodyUnits;
    return custodyUnits.filter((unit) => `${unit.code} ${pickLocalized(unit, 'name', lang)}`.toLocaleLowerCase().includes(needle));
  }, [custodyUnits, unitQuery, lang]);

  const visibleMembers = useMemo(() => {
    const needle = memberQuery.trim().toLocaleLowerCase();
    if (!needle) return employees;
    return employees.filter((employee) => personName(employee, lang).toLocaleLowerCase().includes(needle));
  }, [employees, memberQuery, lang]);

  const submit = async (event) => {
    event.preventDefault();
    if (!draft.name_ar.trim()) { setError(t('error_required_field')); return; }
    if (draft.start_date && draft.end_date && draft.end_date < draft.start_date) {
      setError(t('assets_invalid_date_range'));
      return;
    }
    setBusy(true);
    setError('');
    const { data, error: saveError } = await createInventorySession(draft);
    setBusy(false);
    if (saveError) { setError(assetsErrorMessage(t, saveError)); return; }
    onCreated(data);
  };

  return (
    <div className="modal-backdrop" role="presentation" onClick={onClose}>
      <form
        className="modal-card modal-wide"
        role="dialog"
        aria-modal="true"
        aria-label={t('assets_create_session_title')}
        onClick={(event) => event.stopPropagation()}
        onSubmit={submit}
      >
        <div className="modal-heading">
          <div><span className="section-kicker">{t('module_assets')}</span><h3>{t('assets_create_session_title')}</h3></div>
          <button ref={closeRef} type="button" className="icon-button" onClick={onClose} aria-label={t('action_close')}><X aria-hidden="true" /></button>
        </div>

        <div className="form-grid">
          <label className="field-label">{t('label_name_1')}
            <input required className="form-input" value={draft.name_ar} onChange={field('name_ar')} />
          </label>
          <label className="field-label">{t('label_name_2')}
            <input className="form-input" value={draft.name_en} onChange={field('name_en')} />
          </label>
          <label className="field-label">{t('label_from')}
            <input type="date" className="form-input" value={draft.start_date} onChange={field('start_date')} />
          </label>
          <label className="field-label">{t('label_to')}
            <input type="date" className="form-input" value={draft.end_date} onChange={field('end_date')} />
          </label>
          <label className="field-label field-span-2">{t('assets_field_notes')}
            <textarea className="form-input" value={draft.notes} onChange={field('notes')} />
          </label>
        </div>

        <div className="assets-picker-block">
          <div className="assets-picker-head">
            <b><Boxes size={14} aria-hidden="true" /> {t('assets_field_custody_units_scope')}</b>
            <span className="assets-picker-count">{draft.custody_unit_ids.length}</span>
          </div>
          <div className="search-control compact">
            <Search aria-hidden="true" />
            <input value={unitQuery} onChange={(event) => setUnitQuery(event.target.value)} placeholder={t('action_search')} aria-label={t('assets_field_custody_units_scope')} />
          </div>
          <div className="assets-picker-box">
            {visibleUnits.map((unit) => (
              <label key={unit.id} className="assets-picker-row">
                <input type="checkbox" checked={draft.custody_unit_ids.includes(unit.id)} onChange={() => toggleUnit(unit.id)} />
                <span>{pickLocalized(unit, 'name', lang)}</span>
                <small>{unit.code}</small>
              </label>
            ))}
            {!visibleUnits.length && <p className="assets-picker-empty">{t('label_no_results')}</p>}
          </div>
        </div>

        <div className="assets-picker-block">
          <div className="assets-picker-head">
            <b><Users size={14} aria-hidden="true" /> {t('assets_field_members_scope')}</b>
            <span className="assets-picker-count">{draft.member_user_ids.length}</span>
          </div>
          <div className="search-control compact">
            <Search aria-hidden="true" />
            <input value={memberQuery} onChange={(event) => setMemberQuery(event.target.value)} placeholder={t('action_search')} aria-label={t('assets_field_members_scope')} />
          </div>
          <div className="assets-picker-box">
            {visibleMembers.map((employee) => (
              <label key={employee.id} className="assets-picker-row">
                <input type="checkbox" checked={draft.member_user_ids.includes(employee.id)} onChange={() => toggleMember(employee.id)} />
                <span>{personName(employee, lang)}</span>
                {employee.employee_no && <small>{employee.employee_no}</small>}
              </label>
            ))}
            {!visibleMembers.length && <p className="assets-picker-empty">{t('label_no_results')}</p>}
          </div>
        </div>

        {error && <div className="modal-error"><X aria-hidden="true" />{error}</div>}
        <div className="modal-actions">
          <button type="button" className="secondary-button" onClick={onClose}>{t('action_cancel')}</button>
          <button className="primary-button" disabled={busy}><Plus aria-hidden="true" /> {busy ? t('label_loading') : t('action_save')}</button>
        </div>
      </form>
    </div>
  );
};

// ---------------------------------------------------------------------------
// Complete-session confirmation — shows the tally recorded so far and warns
// that every in-scope asset not yet scanned becomes a Missing row.
// ---------------------------------------------------------------------------
const CompleteSessionModal = ({ reference, tally, busy, onClose, onConfirm }) => {
  const { t } = useLanguage();
  const closeRef = useDialogA11y(onClose);
  return (
    <div className="modal-backdrop" role="presentation" onClick={onClose}>
      <div
        className="modal-card"
        role="dialog"
        aria-modal="true"
        aria-label={t('assets_confirm_complete_title')}
        onClick={(event) => event.stopPropagation()}
      >
        <div className="modal-heading">
          <div><span className="section-kicker">{reference || ''}</span><h3>{t('assets_confirm_complete_title')}</h3></div>
          <button ref={closeRef} type="button" className="icon-button" onClick={onClose} aria-label={t('action_close')}><X aria-hidden="true" /></button>
        </div>
        <p className="field-note">{t('assets_confirm_complete_body')}</p>
        {tally.length > 0 && (
          <ul className="assets-tally-preview">
            {tally.map(([status, count]) => (
              <li key={status}><ScanResultBadge result={status} /><b>{count}</b></li>
            ))}
          </ul>
        )}
        <p className="field-note assets-missing-note"><AlertTriangle size={14} aria-hidden="true" /> {t('assets_confirm_complete_note')}</p>
        <div className="modal-actions">
          <button type="button" className="secondary-button" onClick={onClose}>{t('action_cancel')}</button>
          <button type="button" className="primary-button" disabled={busy} onClick={onConfirm}>
            <ClipboardCheck aria-hidden="true" /> {busy ? t('label_loading') : t('assets_action_complete_session')}
          </button>
        </div>
      </div>
    </div>
  );
};

// ---------------------------------------------------------------------------
// Asset picker — enter/paste a scanned code, or search and pick from the
// list. Free text always survives as the scanned code even when nothing
// matches (an UnexpectedAsset/BarcodeMissing scan has no asset to attach to).
// Same combobox shape as FormsPortal.jsx's SearchableLibrarySelect, kept
// local here since that one is not exported.
// ---------------------------------------------------------------------------
const AssetPicker = ({ assets, lang, query, onQueryChange, onSelect, disabled }) => {
  const { t } = useLanguage();
  const [open, setOpen] = useState(false);
  const needle = query.trim().toLocaleLowerCase();
  const matches = useMemo(() => {
    if (!needle) return [];
    return assets
      .filter((asset) => `${asset.reference} ${asset.name_ar} ${asset.name_en || ''} ${asset.serial_no || ''}`.toLocaleLowerCase().includes(needle))
      .slice(0, 8);
  }, [assets, needle]);

  return (
    <div className="searchable-select" onBlur={(event) => { if (!event.currentTarget.contains(event.relatedTarget)) setOpen(false); }}>
      <Search size={18} aria-hidden="true" />
      <input
        className="form-input"
        role="combobox"
        aria-expanded={open}
        aria-autocomplete="list"
        disabled={disabled}
        value={query}
        placeholder={t('assets_scan_search_placeholder')}
        onFocus={() => setOpen(true)}
        onChange={(event) => onQueryChange(event.target.value)}
      />
      {open && needle && (
        <div className="searchable-options" role="listbox">
          {matches.map((asset) => (
            <button
              type="button"
              role="option"
              key={asset.id}
              onMouseDown={(event) => event.preventDefault()}
              onClick={() => { onSelect(asset); setOpen(false); }}
            >
              <b>{asset.reference}</b>
              <small>{pickLocalized(asset, 'name', lang)}{asset.serial_no ? ` · ${asset.serial_no}` : ''}</small>
            </button>
          ))}
          {!matches.length && <div className="searchable-empty">{t('label_no_results')}</div>}
        </div>
      )}
    </div>
  );
};

// Resolves and renders just the "last transaction" line for one asset.
// Deliberately its own component, remounted via `key={assetId}` by the
// caller: that makes a fresh fetch-on-mount for every newly selected asset
// with `loading` already true from useState's initial value, so — same
// reasoning FormsPortal.jsx documents on its own mount effect — nothing here
// ever needs to call setState synchronously inside the effect body to reset
// stale state from a previous asset.
const LastTransactionInfo = ({ assetId, locale }) => {
  const { t } = useLanguage();
  const [transaction, setTransaction] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    let cancelled = false;
    loadLastMovementForAssets([assetId]).then(({ data }) => {
      if (cancelled) return;
      setTransaction(data?.[assetId] || null);
      setLoading(false);
    });
    return () => { cancelled = true; };
  }, [assetId]);

  if (loading) return t('label_loading');
  if (!transaction) return t('assets_last_transaction_none');
  return `${t(TRANSACTION_TYPE_KEYS[transaction.transactionType] || transaction.transactionType)} · ${formatDate(transaction.performedOn, locale) || '—'}`;
};

// ---------------------------------------------------------------------------
// The scanning/counting interface for an InProgress session.
// ---------------------------------------------------------------------------
const AssetScanForm = ({ sessionId, tenantId, assets, custodyUnitsById, employeesById, lang, locale, onRecorded }) => {
  const { t } = useLanguage();
  const [query, setQuery] = useState('');
  const [assetId, setAssetId] = useState('');
  const [resultStatus, setResultStatus] = useState('');
  const [notes, setNotes] = useState('');
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState('');

  const selectedAsset = useMemo(() => assets.find((asset) => asset.id === assetId) || null, [assets, assetId]);

  const selectAsset = (asset) => {
    setAssetId(asset.id);
    setQuery(asset.reference);
  };

  // Editing the text after picking a match means the person is now typing a
  // different code — the earlier match no longer applies (same "clear the
  // selection the moment free text changes" rule FormsPortal's own
  // SearchableLibrarySelect follows).
  const changeQuery = (value) => {
    setQuery(value);
    if (assetId) setAssetId('');
  };

  const reset = () => {
    setQuery(''); setAssetId(''); setResultStatus(''); setNotes('');
  };

  const submit = async (event) => {
    event.preventDefault();
    if (!resultStatus) { setError(t('assets_scan_pick_result')); return; }
    if (!query.trim() && !assetId) { setError(t('assets_scan_need_code_or_asset')); return; }
    setSubmitting(true);
    setError('');
    const { error: scanError } = await recordInventoryScan(sessionId, resultStatus, {
      scannedCode: query.trim() || null,
      assetId: assetId || null,
      notes: notes.trim() || null,
    });
    setSubmitting(false);
    if (scanError) { setError(assetsErrorMessage(t, scanError)); return; }
    reset();
    onRecorded();
  };

  const expectedCustodyUnit = selectedAsset ? custodyUnitsById[selectedAsset.current_custody_unit_id] : null;
  const expectedCustodian = selectedAsset ? employeesById[selectedAsset.current_custodian_user_id] : null;

  return (
    <form className="assets-scan-form" onSubmit={submit}>
      <label className="field-label">{t('assets_scan_field_label')}
        <AssetPicker assets={assets} lang={lang} query={query} onQueryChange={changeQuery} onSelect={selectAsset} disabled={submitting} />
      </label>

      {selectedAsset && (
        <div className="assets-expected-grid">
          <div><span>{t('assets_expected_name')}</span><b>{pickLocalized(selectedAsset, 'name', lang)}</b></div>
          <div><span>{t('assets_expected_custody_unit')}</span><b>{expectedCustodyUnit ? pickLocalized(expectedCustodyUnit, 'name', lang) : '—'}</b></div>
          <div><span>{t('assets_expected_custodian')}</span><b>{expectedCustodian ? personName(expectedCustodian, lang) : '—'}</b></div>
          <div>
            <span>{t('assets_last_transaction_title')}</span>
            <b><LastTransactionInfo key={selectedAsset.id} assetId={selectedAsset.id} locale={locale} /></b>
          </div>
        </div>
      )}

      <div className="field-label">
        {t('assets_result_status_label')}
        <div className="approval-action-options" role="group" aria-label={t('assets_result_status_label')}>
          {SELECTABLE_SCAN_RESULTS.map((code) => (
            <button
              type="button"
              key={code}
              className={`approval-action-option ${resultStatus === code ? 'active' : ''}`}
              aria-pressed={resultStatus === code}
              onClick={() => setResultStatus(code)}
            >
              <span><b>{t(SCAN_RESULT_KEYS[code])}</b></span>
            </button>
          ))}
        </div>
      </div>

      <label className="field-label">{t('assets_field_notes')}
        <textarea className="form-input" value={notes} onChange={(event) => setNotes(event.target.value)} />
      </label>

      {selectedAsset && tenantId && (
        <div className="assets-scan-photo">
          <p className="field-note">{t('assets_scan_photo_hint')}</p>
          <AttachmentsPanel
            tenantId={tenantId}
            entityType="Asset"
            entityId={selectedAsset.id}
            area="assets"
            layer="Extended"
            listFn={listAssetAttachments}
          />
        </div>
      )}

      {error && <div className="modal-error"><X aria-hidden="true" />{error}</div>}

      <div className="assets-scan-submit">
        <button type="submit" className="primary-button" disabled={submitting}>
          <ClipboardCheck aria-hidden="true" /> {submitting ? t('label_loading') : t('assets_action_record_scan')}
        </button>
      </div>
    </form>
  );
};

// ---------------------------------------------------------------------------
// Scans already recorded for the session.
// ---------------------------------------------------------------------------
const SessionScansTable = ({ scans, assetsById, employeesById, lang, locale }) => {
  const { t } = useLanguage();
  return (
    <div className="data-table-wrap">
      <table className="enterprise-table">
        <thead>
          <tr>
            <th>{t('assets_column_asset')}</th>
            <th>{t('label_status')}</th>
            <th>{t('assets_scanned_by')}</th>
            <th>{t('assets_scanned_on')}</th>
            <th>{t('assets_field_notes')}</th>
          </tr>
        </thead>
        <tbody>
          {scans.map((scan) => {
            const asset = assetsById[scan.asset_id];
            const scannedBy = employeesById[scan.scanned_by];
            return (
              <tr key={scan.id}>
                <td>
                  {asset
                    ? <div><b>{asset.reference}</b><small>{pickLocalized(asset, 'name', lang)}</small></div>
                    : <div><b>{scan.scanned_code || '—'}</b><small>{t('assets_scan_unmatched_asset')}</small></div>}
                </td>
                <td><ScanResultBadge result={scan.result_status} /></td>
                <td>{scannedBy ? personName(scannedBy, lang) : '—'}</td>
                <td>{formatDateTime(scan.scanned_on, locale) || '—'}</td>
                <td>{scan.notes || '—'}</td>
              </tr>
            );
          })}
          {!scans.length && (
            <tr><td colSpan="5"><div className="empty-table compact"><PackageSearch aria-hidden="true" /><b>{t('assets_no_scans_yet')}</b></div></td></tr>
          )}
        </tbody>
      </table>
    </div>
  );
};

// ---------------------------------------------------------------------------
// Session detail: scope, tally, live scanning (InProgress only) and the scan
// history, plus Start/Complete session actions.
// ---------------------------------------------------------------------------
const InventorySessionDetail = ({ sessionId, tenantId, custodyUnits, employees, assets, lang, locale, onBack, onChanged }) => {
  const { t } = useLanguage();
  // `detail` doubles as the loading flag (null = not loaded yet): the effect
  // below only ever sets it from inside the async .then(), so a refresh()
  // never needs a synchronous setState at the top of the effect body — it
  // just re-fetches in the background and swaps `detail` in when ready,
  // which also means an action (start/complete/record a scan) never flashes
  // the whole screen back to a bare loading state.
  const [detail, setDetail] = useState(null);
  const [notice, setNotice] = useState(null);
  const [reloadToken, setReloadToken] = useState(0);
  const [busy, setBusy] = useState(false);
  const [completing, setCompleting] = useState(false);
  const headingRef = useRef(null);
  const focusedOnceRef = useRef(false);

  const custodyUnitsById = useMemo(() => Object.fromEntries(custodyUnits.map((unit) => [unit.id, unit])), [custodyUnits]);
  const employeesById = useMemo(() => Object.fromEntries(employees.map((employee) => [employee.id, employee])), [employees]);
  const assetsById = useMemo(() => Object.fromEntries(assets.map((asset) => [asset.id, asset])), [assets]);

  const refresh = useCallback(() => setReloadToken((value) => value + 1), []);

  useEffect(() => {
    let cancelled = false;
    loadInventorySessionDetail(sessionId).then(({ data, error }) => {
      if (cancelled) return;
      if (error) { setNotice({ tone: 'error', text: assetsErrorMessage(t, error) }); return; }
      setDetail(data);
    });
    return () => { cancelled = true; };
  }, [sessionId, reloadToken, t]);

  // Move focus to the detail heading the moment it first renders (session
  // opened), but not on every later refresh() — focusedOnceRef makes that
  // a one-shot per mount, same as this component's fresh-mount-per-session
  // lifecycle relied on elsewhere in this file.
  useEffect(() => {
    if (detail && !focusedOnceRef.current) {
      focusedOnceRef.current = true;
      headingRef.current?.focus();
    }
  }, [detail]);

  const tally = useMemo(() => {
    if (!detail) return [];
    const counts = new Map();
    detail.scans.forEach((scan) => counts.set(scan.result_status, (counts.get(scan.result_status) || 0) + 1));
    return [...counts.entries()];
  }, [detail]);

  const missingCount = tally.find(([status]) => status === 'Missing')?.[1] || 0;

  const start = async () => {
    setBusy(true);
    const { error } = await startInventorySession(sessionId);
    setBusy(false);
    if (error) { setNotice({ tone: 'error', text: assetsErrorMessage(t, error) }); return; }
    setNotice({ tone: 'success', text: t('assets_session_started') });
    refresh();
    onChanged?.();
  };

  const confirmComplete = async () => {
    setBusy(true);
    const { error } = await completeInventorySession(sessionId);
    setBusy(false);
    setCompleting(false);
    if (error) { setNotice({ tone: 'error', text: assetsErrorMessage(t, error) }); return; }
    setNotice({ tone: 'success', text: t('assets_session_completed') });
    refresh();
    onChanged?.();
  };

  if (!detail) {
    return (
      <div className="admin-content">
        <div className="assets-detail-head">
          <button type="button" className="secondary-button" onClick={onBack}><ArrowLeft aria-hidden="true" /> {t('assets_back_to_sessions')}</button>
        </div>
        <Notice notice={notice} onDismiss={() => setNotice(null)} />
        {!notice && <p className="field-note">{t('label_loading')}</p>}
      </div>
    );
  }

  const { session, units, members, scans } = detail;
  const scopeUnits = units.map((row) => custodyUnitsById[row.custody_unit_id]).filter(Boolean);
  const scopeMembers = members.map((row) => employeesById[row.user_id]).filter(Boolean);

  return (
    <div className="admin-content">
      <div className="assets-detail-head">
        <button type="button" className="secondary-button" onClick={onBack}><ArrowLeft aria-hidden="true" /> {t('assets_back_to_sessions')}</button>
      </div>

      <div className="admin-toolbar">
        <div>
          <span className="section-kicker">{session.reference}</span>
          <h1 ref={headingRef} tabIndex={-1}>{pickLocalized(session, 'name', lang) || t('assets_inventory_title')}</h1>
          <p><StatusBadge status={session.status} /></p>
        </div>
        <div className="toolbar-buttons">
          {session.status === 'Draft' && (
            <button type="button" className="primary-button" disabled={busy} onClick={start}>
              <Play aria-hidden="true" /> {t('assets_action_start_session')}
            </button>
          )}
          {session.status === 'InProgress' && (
            <button type="button" className="primary-button" disabled={busy} onClick={() => setCompleting(true)}>
              <ClipboardCheck aria-hidden="true" /> {t('assets_action_complete_session')}
            </button>
          )}
          <button type="button" className="secondary-button" onClick={refresh}><RefreshCcw aria-hidden="true" /> {t('action_refresh')}</button>
        </div>
      </div>

      <Notice notice={notice} onDismiss={() => setNotice(null)} />

      <section className="dashboard-panel">
        <h3><Calendar aria-hidden="true" /> {t('assets_session_period')}</h3>
        <div className="assets-expected-grid">
          <div><span>{t('label_from')}</span><b>{formatDate(session.start_date, locale) || '—'}</b></div>
          <div><span>{t('label_to')}</span><b>{formatDate(session.end_date, locale) || '—'}</b></div>
          <div><span>{t('label_created_on')}</span><b>{formatDate(session.created_on, locale) || '—'}</b></div>
        </div>
        {session.notes && <p className="field-note">{session.notes}</p>}
        {scopeUnits.length > 0 && (
          <>
            <p className="field-note">{t('assets_field_custody_units_scope')}</p>
            <div className="assets-chip-row">
              {scopeUnits.map((unit) => <span key={unit.id} className="assets-chip"><Boxes aria-hidden="true" /> {pickLocalized(unit, 'name', lang)}</span>)}
            </div>
          </>
        )}
        {scopeMembers.length > 0 && (
          <>
            <p className="field-note">{t('assets_field_members_scope')}</p>
            <div className="assets-chip-row">
              {scopeMembers.map((member) => <span key={member.id} className="assets-chip"><Users aria-hidden="true" /> {personName(member, lang)}</span>)}
            </div>
          </>
        )}
      </section>

      {tally.length > 0 && (
        <section className="dashboard-panel">
          <h3><ListChecks aria-hidden="true" /> {t('assets_summary_title')}</h3>
          <div className="kpi-grid compact">
            {tally.map(([status, count]) => (
              <div className="kpi-card" key={status}>
                <Package aria-hidden="true" />
                <div><span>{SCAN_RESULT_KEYS[status] ? t(SCAN_RESULT_KEYS[status]) : status}</span><b>{count}</b></div>
              </div>
            ))}
          </div>
          {session.status === 'Completed' && (
            <p className="field-note assets-missing-note"><AlertTriangle size={14} aria-hidden="true" /> {t('assets_summary_missing_generated', { count: missingCount })}</p>
          )}
        </section>
      )}

      {session.status === 'InProgress' && (
        <section className="dashboard-panel">
          <h3><Barcode aria-hidden="true" /> {t('assets_scan_title')}</h3>
          <AssetScanForm
            sessionId={sessionId}
            tenantId={tenantId}
            assets={assets}
            custodyUnitsById={custodyUnitsById}
            employeesById={employeesById}
            lang={lang}
            locale={locale}
            onRecorded={() => { setNotice({ tone: 'success', text: t('assets_scan_saved') }); refresh(); }}
          />
        </section>
      )}

      <section className="dashboard-panel">
        <h3><ClipboardList aria-hidden="true" /> {t('assets_scans_table_title')}</h3>
        <SessionScansTable scans={scans} assetsById={assetsById} employeesById={employeesById} lang={lang} locale={locale} />
      </section>

      {completing && (
        <CompleteSessionModal
          reference={session.reference}
          tally={tally}
          busy={busy}
          onClose={() => setCompleting(false)}
          onConfirm={confirmComplete}
        />
      )}
    </div>
  );
};

// ---------------------------------------------------------------------------
// Sessions list — the screen's landing view.
// ---------------------------------------------------------------------------
const SessionsListView = ({ sessions, loading, notice, onDismissNotice, lang, locale, statusFilter, setStatusFilter, search, setSearch, onOpen, onCreate }) => {
  const { t } = useLanguage();
  const headingRef = useRef(null);

  // This view unmounts entirely while a session's detail is open (see the
  // selectedId branch in AssetInventoryAdmin below), so every mount here is
  // either the initial load or "came back from detail" — same one-effect
  // shape AssetsPortal.jsx's own list/detail toggle already uses.
  useEffect(() => { headingRef.current?.focus(); }, []);

  const filtered = useMemo(() => {
    const needle = search.trim().toLocaleLowerCase();
    return sessions.filter((session) => (
      (statusFilter === 'All' || session.status === statusFilter)
      && (!needle || `${session.reference} ${session.name_ar} ${session.name_en || ''}`.toLocaleLowerCase().includes(needle))
    ));
  }, [sessions, statusFilter, search]);

  return (
    <div className="admin-content">
      <div className="admin-toolbar">
        <div>
          <span className="section-kicker">{t('module_assets')}</span>
          <h1 ref={headingRef} tabIndex={-1}><ClipboardList className="admin-title-icon" aria-hidden="true" /> {t('assets_inventory_title')}</h1>
          <p>{t('assets_inventory_intro')}</p>
        </div>
        <div className="toolbar-actions">
          <button type="button" className="primary-button" onClick={onCreate}><Plus aria-hidden="true" /> {t('assets_inventory_new_session')}</button>
        </div>
      </div>

      <Notice notice={notice} onDismiss={onDismissNotice} />

      <div className="data-controls">
        <div className="search-control">
          <Search aria-hidden="true" />
          <input
            value={search}
            onChange={(event) => setSearch(event.target.value)}
            placeholder={t('assets_inventory_search_placeholder')}
            aria-label={t('action_search')}
          />
        </div>
        <div className="segmented" role="group" aria-label={t('label_status')}>
          {SESSION_STATUS_FILTERS.map((status) => (
            <button
              type="button"
              key={status}
              aria-pressed={statusFilter === status}
              className={statusFilter === status ? 'active' : ''}
              onClick={() => setStatusFilter(status)}
            >
              {status === 'All' ? t('label_all') : t(SESSION_STATUS_KEYS[status])}
            </button>
          ))}
        </div>
      </div>

      <div className="data-table-wrap">
        <table className="enterprise-table">
          <thead>
            <tr>
              <th>{t('assets_column_reference')}</th>
              <th>{t('label_status')}</th>
              <th>{t('assets_session_period')}</th>
              <th aria-label={t('label_actions')} />
            </tr>
          </thead>
          <tbody>
            {filtered.map((session) => (
              <tr key={session.id}>
                <td><div><b>{session.reference}</b><small>{pickLocalized(session, 'name', lang)}</small></div></td>
                <td><StatusBadge status={session.status} /></td>
                <td>{formatDate(session.start_date, locale) || '—'} – {formatDate(session.end_date, locale) || '—'}</td>
                <td>
                  <div className="table-actions">
                    <button type="button" onClick={() => onOpen(session.id)} title={t('action_open')} aria-label={t('action_open')}><Eye aria-hidden="true" /></button>
                  </div>
                </td>
              </tr>
            ))}
            {!loading && !filtered.length && (
              <tr><td colSpan="4"><div className="empty-table"><PackageSearch aria-hidden="true" /><b>{t('label_no_results')}</b><span>{t('assets_session_empty_hint')}</span></div></td></tr>
            )}
            {loading && <tr><td colSpan="4">{t('label_loading')}</td></tr>}
          </tbody>
        </table>
      </div>
    </div>
  );
};

// ---------------------------------------------------------------------------
// Entry point.
// ---------------------------------------------------------------------------
const AssetInventoryAdmin = () => {
  const { t, lang, locale } = useLanguage();
  const { tenant } = useTenant();

  const [sessions, setSessions] = useState([]);
  const [sessionsLoading, setSessionsLoading] = useState(true);
  const [notice, setNotice] = useState(null);
  const [reloadToken, setReloadToken] = useState(0);
  const [selectedId, setSelectedId] = useState(null);
  const [creating, setCreating] = useState(false);
  const [statusFilter, setStatusFilter] = useState('All');
  const [search, setSearch] = useState('');

  const [custodyUnits, setCustodyUnits] = useState([]);
  const [employees, setEmployees] = useState([]);
  const [assets, setAssets] = useState([]);

  // refresh() itself sets sessionsLoading synchronously (it runs from an
  // event handler, not an effect body) before bumping the token — same
  // "caller sets loading, the effect's .then() clears it" split
  // OrgEntityScreen.jsx's own refresh() uses, so the fetch effect below
  // never calls setState synchronously in its own body.
  const refreshSessions = useCallback(() => {
    setSessionsLoading(true);
    setReloadToken((value) => value + 1);
  }, []);

  useEffect(() => {
    let cancelled = false;
    loadInventorySessions().then(({ data, error }) => {
      if (cancelled) return;
      if (error) setNotice({ tone: 'error', text: assetsErrorMessage(t, error) });
      else setSessions(data || []);
      setSessionsLoading(false);
    });
    return () => { cancelled = true; };
  }, [reloadToken, t]);

  // The directory (custody units / company assets / employee directory) does
  // not depend on the sessions filter/search state, and is shared by both
  // the create-session modal and the scanning screen — fetched once, plus
  // whenever the language changes (harmless refetch, not data loss, since
  // nothing here is user-entered).
  useEffect(() => {
    let cancelled = false;
    Promise.all([loadCustodyUnits(), loadAssets({}), loadRecipients().catch(() => [])])
      .then(([unitsResult, assetsResult, employeesData]) => {
        if (cancelled) return;
        setCustodyUnits(unitsResult.data || []);
        setAssets(assetsResult.data || []);
        setEmployees(employeesData || []);
        if (unitsResult.error || assetsResult.error) {
          setNotice({ tone: 'error', text: assetsErrorMessage(t, unitsResult.error || assetsResult.error) });
        }
      });
    return () => { cancelled = true; };
  }, [t]);

  const openSession = (id) => setSelectedId(id);
  const backToList = () => { setSelectedId(null); refreshSessions(); };

  if (selectedId) {
    return (
      <InventorySessionDetail
        sessionId={selectedId}
        tenantId={tenant?.id}
        custodyUnits={custodyUnits}
        employees={employees}
        assets={assets}
        lang={lang}
        locale={locale}
        onBack={backToList}
        onChanged={refreshSessions}
      />
    );
  }

  return (
    <>
      <SessionsListView
        sessions={sessions}
        loading={sessionsLoading}
        notice={notice}
        onDismissNotice={() => setNotice(null)}
        lang={lang}
        locale={locale}
        statusFilter={statusFilter}
        setStatusFilter={setStatusFilter}
        search={search}
        setSearch={setSearch}
        onOpen={openSession}
        onCreate={() => setCreating(true)}
      />
      {creating && (
        <CreateSessionModal
          custodyUnits={custodyUnits}
          employees={employees}
          lang={lang}
          onClose={() => setCreating(false)}
          onCreated={(id) => {
            setCreating(false);
            refreshSessions();
            setNotice({ tone: 'success', text: t('assets_session_created') });
            if (id) setSelectedId(id);
          }}
        />
      )}
    </>
  );
};

export default AssetInventoryAdmin;